kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: false
  podSubnet: 10.202.0.0/16
  serviceSubnet: 100.22.0.0/16
  kubeProxyMode: iptables
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "127.0.0.1"
        - "cluster2.local"
        - "10.29.30.4"     # Replace with your cluster internal IP
        - "204.101.38.113" # Replace with your cluster public IP
nodes:
  - role: control-plane
    extraPortMappings:
    # Required for Submariner to establish gateway connections
    - containerPort: 4500
      hostPort: 4500
      protocol: UDP
  - role: worker