kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: 10.253.0.0/24
  serviceSubnet: 10.253.1.0/24
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "127.0.0.1"
        - "0.0.0.0"
        - "c1.local"
        - "10.30.20.18"    # Replace with your cluster internal IP
        - "142.1.174.178"  # Replace with your cluster public IP
nodes:
  - role: control-plane
    extraPortMappings:
    # Required for inter-cluster communication
    - containerPort: 4500
      hostPort: 4500
      protocol: UDP
  - role: worker
